# -*- coding: utf-8 -*-
"""PROG | - Exércicios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSgxtOEDIfK9YDB86FRP2Yrmh5WocyX2
"""

#Exercicío 1 da Lista 000(Possibilidade de Melhora)
#import math

mil = float(input("Digite a quantidade de segundos do evento: "))
if mil%2 ==0:
    seg = mil/1000
    qtd_total_min = mil/60
    qtd_total_hor = qtd_total_min / 60
    qtd_total_hors = str(qtd_total_hor)[:2]
    print(f'A Duração do evento e {seg} segundo e {qtd_total_min:.0f} minutos e {qtd_total_hors} horas')

###############################################################################################################################

ms = float(input("Digite a quantidade de segundos do evento: "))
s = ms//1000
h = s//360
s = s%360
m = s//60
s = s% 60
print(f'A quantidade total de segundos foi {s} e o total de horas foi {h} o de minutos {m}')


